services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cordon.account_review.entity_locator:
    class: Cordon\AccountReview\EntityLocator

  Cordon\AccountReview\Command\AccountReviewCommand:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $serializer: '@serializer'
      $entityLocator: '@cordon.account_review.entity_locator'
    tags:
      - { name: 'console.command' }
